name: CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test-the-project:
    needs: setup
    uses: ./.github/workflows/test.yml

  send-code-coverage:
    needs: test-the-project
    uses: ./.github/workflows/send-coverage.yml

  generate-lint:
    needs: setup
    uses: ./.github/workflows/lint.yml
