name: Generate lint

on: workflow_call

jobs:
  run-tests:
    name: Generate lint
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: npm run lint-html
      - name: Upload the lint HTML report
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: lint.html
