name: Publish a new release of the library to GitHub Packages

on:
  push:
    tags:
      - v*

jobs:
  run-tests:
    name: Test the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup the Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install the package and its dependencies
        run: npm install
      - name: Set path to a chromium browser (needed for screenshot tests)
        run: |
          echo "{\"chromiumPath\": \"$(which chromium)\"}" > local.json
      - name: Run the tests (with coverage)
        id: steps-test-run
        run: ./node_modules/.bin/jest --ci --colors --coverage
      - name: Upload the test report
        if: always() # Run even if the previous steps failed
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: |
            test-report.xml
            test-report.html
      - name: Upload the test coverage report
        if: ${{ steps.steps-test-run.conclusion == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/
      - name: Run lint
        run: npm run lint-html
      - name: Upload the lint HTML report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: lint.html

  merge-into-prod:
    needs: [ run-tests ]
    name: Rebase (fast forward) the prod branch onto the master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: emiliopedrollo/auto-merge@v1.2.0
        with:
          target_branch: 'prod'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-the-package:
    needs: [ run-tests ]
    name: Publish the artifacts to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup the Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install the package and its dependencies
        run: npm install
      # See https://sevic.dev/npm-publish-github-actions/
      - name: Set npm package registry to GitHub Packages
        run: npm config set registry https://npm.pkg.github.com
      - name: Authenticate to GitHub Packages registry
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      # - name: Authenticate to npm registry
      #   run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish the package to GitHub Packages registry # And others registries like npm, if authenticated
        run: npm publish

  create-github-release:
    needs: [ publish-the-package ]
    name: Create a new release in the GitHub repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Generate the changelog
        run: kotlin .github/scripts/generate-github-changelog.main.kts
      - name: Create the release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.txt
          files: theme-switch.min.js
