name: Set the project up

on: workflow_call

jobs:
  setup:
    name: Set the project up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install the library and its dependencies
        run: npm install
