name: Test the project

on: workflow_call

jobs:
  run-tests:
    name: Test the project
    runs-on: ubuntu-latest
    steps:
      - name: Set path to a chromium browser (needed for screenshot tests)
        # See https://stackoverflow.com/a/57627150/8583692
        # and https://stackoverflow.com/a/4181721/8583692
        run: |
          echo "{\"chromiumPath\": \"$(which chromium)\"}" > local.json
      - name: Run the tests (with coverage)
        id: run-tests
        run: ./node_modules/.bin/jest --ci --colors --coverage # OR npm run test-with-coverage
      - name: Upload the test report
        if: always() # Run even if the previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            test-report.xml
            test-report.html
